(function () {
  window.GYM_DATA = {
    gym: {
      name: "Iron Force Gym",
      logo: "assets/placeholder.svg",
      cuit: "30-71234567-9",
      whatsapp: "+54 11 5555-1234",
      instagram: "@ironforcegym",
      web: "www.ironforcegym.com",
      slogan: "Transformá tu cuerpo, transformá tu vida",
      heroSubtitle:
        "Más de 15 años formando campeones. Entrenamiento personalizado con los mejores profesionales del país.",
    },
    metrics: [
      { label: "Alumnos activos", value: 500, prefix: "+" },
      { label: "Sedes", value: 3 },
      { label: "Años de experiencia", value: 15 },
      { label: "Entrenadores de élite", value: 20 },
    ],
    sedes: [
      {
        id: "sede-1",
        name: "Sede Centro",
        address: "Av. Corrientes 1234, CABA",
        hours: "Lun a Vie 6:00 - 23:00 | Sáb 8:00 - 20:00",
        description:
          "Nuestra sede principal con 800m² de equipamiento de última generación, zona de peso libre, cardio y salas de clases grupales.",
        image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
        phone: "+54 11 5555-1001",
      },
      {
        id: "sede-2",
        name: "Sede Norte",
        address: "Av. Libertador 5678, Vicente López",
        hours: "Lun a Vie 7:00 - 22:00 | Sáb 9:00 - 18:00",
        description:
          "Espacio premium con pileta climatizada, zona funcional al aire libre y estacionamiento privado.",
        image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&q=80",
        phone: "+54 11 5555-1002",
      },
      {
        id: "sede-3",
        name: "Sede Sur",
        address: "Av. Almafuerte 910, Lanús",
        hours: "Lun a Sáb 7:00 - 22:00",
        description:
          "Sede especializada en crossfit y entrenamiento funcional con boxes de última generación.",
        image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&q=80",
        phone: "+54 11 5555-1003",
      },
    ],
    trainers: [
      {
        id: "t1",
        name: "Martín Rodríguez",
        specialty: "Musculación",
        sedeId: "sede-1",
        sedeName: "Sede Centro",
        bio: "10 años de experiencia en preparación física y competición.",
        image: "https://images.unsplash.com/photo-1567013127542-490d483e18e4?w=400&q=80",
      },
      {
        id: "t2",
        name: "Lucía Fernández",
        specialty: "Funcional",
        sedeId: "sede-1",
        sedeName: "Sede Centro",
        bio: "Certificada en CrossFit L3 y especialista en movilidad.",
        image: "https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400&q=80",
      },
      {
        id: "t3",
        name: "Diego Martínez",
        specialty: "CrossFit",
        sedeId: "sede-3",
        sedeName: "Sede Sur",
        bio: "Ex competidor nacional, coach desde 2016.",
        image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&q=80",
      },
      {
        id: "t4",
        name: "Sofía López",
        specialty: "Yoga & Pilates",
        sedeId: "sede-2",
        sedeName: "Sede Norte",
        bio: "Instructora certificada con enfoque en bienestar integral.",
        image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&q=80",
      },
      {
        id: "t5",
        name: "Carlos Gómez",
        specialty: "Boxeo",
        sedeId: "sede-1",
        sedeName: "Sede Centro",
        bio: "Entrenador de boxeo recreativo y competitivo.",
        image: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=400&q=80",
      },
      {
        id: "t6",
        name: "Ana Sánchez",
        specialty: "Nutrición Deportiva",
        sedeId: "sede-2",
        sedeName: "Sede Norte",
        bio: "Lic. en Nutrición con posgrado en deporte de alto rendimiento.",
        image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80",
      },
    ],
    plans: [
      {
        id: "p1",
        name: "Plan Mensual",
        price: 25000,
        enrollment: 5000,
        duration: "1 mes",
        benefits: ["Acceso a musculación", "Clases grupales", "Vestuario con ducha"],
        recommended: false,
        active: true,
        sedeId: null,
      },
      {
        id: "p2",
        name: "Plan Semestral",
        price: 120000,
        enrollment: 0,
        duration: "6 meses",
        benefits: [
          "Todo del Plan Mensual",
          "Matrícula bonificada",
          "1 clase personal/mes",
          "Acceso a todas las sedes",
        ],
        recommended: true,
        active: true,
        sedeId: null,
      },
      {
        id: "p3",
        name: "Plan Anual VIP",
        price: 200000,
        enrollment: 0,
        duration: "12 meses",
        benefits: [
          "Todo del Plan Semestral",
          "Nutricionista incluido",
          "2 clases personales/mes",
          "Locker premium",
          "Acceso 24/7",
        ],
        recommended: false,
        active: true,
        sedeId: null,
      },
    ],
    testimonials: [
      {
        id: "ts1",
        name: "Juan Pérez",
        activity: "Musculación",
        text: "En 6 meses logré resultados que no había conseguido en años. El seguimiento personalizado marca la diferencia.",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
      },
      {
        id: "ts2",
        name: "María García",
        activity: "Funcional",
        text: "El ambiente es increíble, los profes te motivan y la comunidad te acompaña. No volvería a entrenar en otro lado.",
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
      },
      {
        id: "ts3",
        name: "Roberto Silva",
        activity: "CrossFit",
        text: "Vine por curiosidad y me quedé por los resultados. Bajé 15 kilos y gané confianza.",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
      },
      {
        id: "ts4",
        name: "Laura Méndez",
        activity: "Yoga",
        text: "Encontré un espacio de paz dentro del gimnasio. Las clases de yoga son un oasis en mi semana.",
        image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
      },
    ],
    license: {
      id: "LIC-2024-00142",
      version: "3.2.1",
      plan: "Profesional",
      expiresAt: "2026-12-31",
      maxMembers: 600,
      currentMembers: 487,
      status: "active",
    },
    modules: [
      {
        id: "access",
        name: "Control de Acceso",
        description: "Huella digital, RFID y placas de acceso",
        enabled: true,
      },
      {
        id: "sales",
        name: "Ventas",
        description: "Lectores de código de barras para productos",
        enabled: false,
      },
      {
        id: "bookings",
        name: "Reservas de Turnos",
        description: "Gestión de reservas para clases y actividades",
        enabled: true,
      },
      {
        id: "comms",
        name: "Comunicación Masiva",
        description: "WhatsApp automáticos y campañas segmentadas",
        enabled: true,
      },
      {
        id: "routines",
        name: "Rutinas y Seguimiento",
        description: "Constructor de rutinas y registro de cargas",
        enabled: true,
      },
    ],
    dashboardMetrics: {
      todayIncome: 185400,
      activeMembers: 487,
      todayAttendance: 124,
      expiringMemberships: 18,
    },
    weeklyIncome: [
      { day: "Lun", amount: 42000 },
      { day: "Mar", amount: 38500 },
      { day: "Mié", amount: 51200 },
      { day: "Jue", amount: 29800 },
      { day: "Vie", amount: 45600 },
      { day: "Sáb", amount: 32100 },
      { day: "Dom", amount: 0 },
    ],
    monthlyAttendance: [
      { week: "Sem 1", count: 580 },
      { week: "Sem 2", count: 620 },
      { week: "Sem 3", count: 540 },
      { week: "Sem 4", count: 690 },
    ],
    users: [
      { id: "u1", name: "Admin Principal", email: "admin@ironforce.com", role: "Super Admin", status: "active" },
      { id: "u2", name: "Carlos Dueño", email: "carlos@ironforce.com", role: "Dueño", status: "active" },
      { id: "u3", name: "Martín Rodríguez", email: "martin@ironforce.com", role: "Profesor", status: "active" },
      { id: "u4", name: "Lucía Fernández", email: "lucia@ironforce.com", role: "Profesor", status: "active" },
      { id: "u5", name: "Pedro Recepción", email: "pedro@ironforce.com", role: "Empleado", status: "active" },
      { id: "u6", name: "Juan Pérez", email: "juan@email.com", role: "Socio", status: "active" },
      { id: "u7", name: "María García", email: "maria@email.com", role: "Socio", status: "inactive" },
    ],

    /** Socios demo para control de acceso (se clonan a localStorage al primer uso) */
    sociosSeed: [
      {
        id: "soc-demo-1",
        dni: "30123456",
        firstName: "María",
        lastName: "González",
        phone: "+54 11 6000-1111",
        activity: "Musculación",
        planId: "p2",
        planName: "Plan Semestral",
        expiresAt: "2026-04-15",
        debt: 0,
        birthDate: "1990-05-10",
        payments: [
          { id: "pay-1", at: "2026-03-15T10:00:00.000Z", amount: 120000, method: "Transferencia", concept: "Plan Semestral" },
        ],
      },
      {
        id: "soc-demo-2",
        dni: "28999887",
        firstName: "Marcelo",
        lastName: "Díaz",
        phone: "+54 11 6000-2222",
        activity: "Funcional",
        planId: "p1",
        planName: "Plan Mensual",
        expiresAt: "2026-03-18",
        debt: 500,
        birthDate: "1988-11-22",
        payments: [],
      },
      {
        id: "soc-demo-3",
        dni: "25444111",
        firstName: "Ricardo",
        lastName: "Luna",
        phone: "+54 11 6000-3333",
        activity: "CrossFit",
        planId: "p1",
        planName: "Plan Mensual",
        expiresAt: "2026-02-10",
        debt: 0,
        birthDate: "1995-03-05",
        payments: [],
      },
    ],

    whatsappAutomationDefaults: [
      {
        id: "wa-recibo",
        name: "Recibo de pago",
        enabled: true,
        body: "Hola [nombre], recibimos tu pago de [monto]. ¡Gracias por confiar en [gimnasio]!",
      },
      {
        id: "wa-vence",
        name: "Aviso de vencimiento de cuota",
        enabled: true,
        body: "Hola [nombre], te recordamos que tu cuota vence el [vencimiento]. Podés acercarte a recepción para renovar.",
      },
      {
        id: "wa-deuda",
        name: "Saldo pendiente",
        enabled: true,
        body: "Hola [nombre], tenés un saldo pendiente de [deuda]. Cualquier consulta, escribinos.",
      },
      {
        id: "wa-winback",
        name: "Invitación a volver",
        enabled: false,
        body: "Hola [nombre], te extrañamos en [gimnasio]. Si querés retomar, tenemos promos especiales.",
      },
    ],

    /**
     * Cuentas demo para el panel (login: DNI + contraseña).
     * Contraseña común de demo: demo123
     */
    demoStaffAccounts: [
      { dni: "20111222", password: "demo123", displayName: "Ana Recepción", role: "Recepción" },
      { dni: "20999888", password: "demo123", displayName: "Carlos Dueño", role: "Dueño" },
      { dni: "18777666", password: "demo123", displayName: "Martín Profesor", role: "Profesor" },
      { dni: "16555444", password: "demo123", displayName: "Lucía Admin", role: "Super Admin" },
    ],

    /** Productos demo para ventas / stock (localStorage tras primer cambio) */
    productsSeed: [
      { id: "prod-1", name: "Shaker 700ml", sku: "7790001001001", price: 8500, stock: 40 },
      { id: "prod-2", name: "Proteína 1 kg", sku: "7790001002002", price: 42000, stock: 18 },
      { id: "prod-3", name: "Barrita proteica (u)", sku: "7790001003003", price: 1200, stock: 120 },
      { id: "prod-4", name: "Toalla microfibra", sku: "7790001004004", price: 6500, stock: 25 },
      { id: "prod-5", name: "Bebida isotónica 500ml", sku: "7790001005005", price: 1800, stock: 60 },
    ],

    /** Ingresos simulados por franja horaria (lunes típico) */
    statsByHour: [
      { h: "6-8", n: 42 },
      { h: "8-10", n: 28 },
      { h: "10-12", n: 15 },
      { h: "12-14", n: 35 },
      { h: "14-18", n: 22 },
      { h: "18-20", n: 58 },
      { h: "20-22", n: 44 },
    ],
  };
})();
